### ISSUE TITLE
subfolder for demo scripts ?

### ISSUE THREAD

**Issue by theinze** [joha2/pyrate#20]
Move `demo_*.py` into project subfolder ?

Btw which demos are suitable for the image comparison (i.e., which demos should provide a more or less stable result) ? Currently only `demo_doublet.py` is used.

Btwbtw there are some `RuntimeWarning: invalid value encountered in ...` warnings, coming from numpy, is that an issue ?

**Comment by joha2** [comment]
Moving the demo_*.py files into some subfolder would be good for our project structure but not that good for visibility. Maybe a compromise on this is to move them into some demos/ subfolder.

The demos show some core functionality of pyrate and they are starting points for the users. I think really stable is only the doublet and the prism demo. The rest is subject to change if there are some changes in the core functionality of pyrate. At least we have to check their functionality before by using some test oracle ;-)

The invalid value encountered are due to numerical instabilities of the explicit solution formulas in the conic section surfShape class. I'm not quite sure if this is an issue, since all `invalid values` are defined as invalid after they appear in the intersect function.
