### ISSUE TITLE
repair demos

### ISSUE THREAD

**Issue by mess42** [joha2/pyrate#23]
Since the demos are moved, I can't start the demos from console any more.

$ cd python/pyrate/demos
$ python demo_doublet.py
Traceback (most recent call last):
  File "demo_doublet.py", line 39, in <module>
    from core import raster
ImportError: No module named core

**Comment by joha2** [comment]
Yeah you cannot start them by simply calling python due to the strange import mechanism.
But it is still possible to write:
`~/pyrate$ python -m demos.demo_doublet` (i.e. to load demo_doublet module as script).
Help for python says: `-m mod : run library module as a script (terminates option list)`.
